// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: layer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Variations {

  /// <summary>Holder for reflection information generated from layer.proto</summary>
  public static partial class LayerReflection {

    #region Descriptor
    /// <summary>File descriptor for layer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtsYXllci5wcm90bxIKdmFyaWF0aW9ucyLHAgoFTGF5ZXISCgoCaWQYASAB",
            "KA0SEQoJbnVtX3Nsb3RzGAIgASgNEi4KB21lbWJlcnMYAyADKAsyHS52YXJp",
            "YXRpb25zLkxheWVyLkxheWVyTWVtYmVyEgwKBHNhbHQYBCABKA0SMwoMZW50",
            "cm9weV9tb2RlGAUgASgOMh0udmFyaWF0aW9ucy5MYXllci5FbnRyb3B5TW9k",
            "ZRp6CgtMYXllck1lbWJlchIKCgJpZBgBIAEoDRI2CgVzbG90cxgCIAMoCzIn",
            "LnZhcmlhdGlvbnMuTGF5ZXIuTGF5ZXJNZW1iZXIuU2xvdFJhbmdlGicKCVNs",
            "b3RSYW5nZRINCgVzdGFydBgBIAEoDRILCgNlbmQYAiABKA0iMAoLRW50cm9w",
            "eU1vZGUSCwoHREVGQVVMVBAAEgcKA0xPVxABEgsKB0xJTUlURUQQAiJfChRM",
            "YXllck1lbWJlclJlZmVyZW5jZRIQCghsYXllcl9pZBgBIAEoDRIXCg9sYXll",
            "cl9tZW1iZXJfaWQYAiABKA0SHAoQbGF5ZXJfbWVtYmVyX2lkcxgDIAMoDUIC",
            "EAFCJgoib3JnLmNocm9taXVtLmNvbXBvbmVudHMudmFyaWF0aW9uc0gD"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Variations.Layer), global::Variations.Layer.Parser, new[]{ "Id", "NumSlots", "Members", "Salt", "EntropyMode" }, null, new[]{ typeof(global::Variations.Layer.Types.EntropyMode) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Variations.Layer.Types.LayerMember), global::Variations.Layer.Types.LayerMember.Parser, new[]{ "Id", "Slots" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Variations.Layer.Types.LayerMember.Types.SlotRange), global::Variations.Layer.Types.LayerMember.Types.SlotRange.Parser, new[]{ "Start", "End" }, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Variations.LayerMemberReference), global::Variations.LayerMemberReference.Parser, new[]{ "LayerId", "LayerMemberId", "LayerMemberIds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Next tag: 6
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Layer : pb::IMessage<Layer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Layer> _parser = new pb::MessageParser<Layer>(() => new Layer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Layer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Variations.LayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Layer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Layer(Layer other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      numSlots_ = other.numSlots_;
      members_ = other.members_.Clone();
      salt_ = other.salt_;
      entropyMode_ = other.entropyMode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Layer Clone() {
      return new Layer(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static uint IdDefaultValue = 0;

    private uint id_;
    /// <summary>
    /// ID for the layer, must be unique across all layers. Studies will specify
    /// a &lt;layer_id, layer_member_id> pair to become part of a layer.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "num_slots" field.</summary>
    public const int NumSlotsFieldNumber = 2;
    private readonly static uint NumSlotsDefaultValue = 0;

    private uint numSlots_;
    /// <summary>
    /// Total number of slots within the layer. There are constraints on the number
    /// of slots when a low entropy source is used (100, initially) to alleviate
    /// skew in the bucket populations.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumSlots {
      get { if ((_hasBits0 & 2) != 0) { return numSlots_; } else { return NumSlotsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        numSlots_ = value;
      }
    }
    /// <summary>Gets whether the "num_slots" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumSlots {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "num_slots" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumSlots() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Variations.Layer.Types.LayerMember> _repeated_members_codec
        = pb::FieldCodec.ForMessage(26, global::Variations.Layer.Types.LayerMember.Parser);
    private readonly pbc::RepeatedField<global::Variations.Layer.Types.LayerMember> members_ = new pbc::RepeatedField<global::Variations.Layer.Types.LayerMember>();
    /// <summary>
    /// Layer members, which occupy disjoint subsets of the [0, `num_slots`) range.
    /// Not all slots have to be used, and normally won't in order to reserve space
    /// within the layer. Each study that participates in a layer is associated
    /// with a single layer member.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Variations.Layer.Types.LayerMember> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "salt" field.</summary>
    public const int SaltFieldNumber = 4;
    private readonly static uint SaltDefaultValue = 0;

    private uint salt_;
    /// <summary>
    /// A salt which is used as an input to a hash function together with the
    /// output of the chosen entropy source, to choose an active slot within the
    /// layer. If salt is unset or 0, the layer id will be used instead.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Salt {
      get { if ((_hasBits0 & 4) != 0) { return salt_; } else { return SaltDefaultValue; } }
      set {
        _hasBits0 |= 4;
        salt_ = value;
      }
    }
    /// <summary>Gets whether the "salt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSalt {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "salt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSalt() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "entropy_mode" field.</summary>
    public const int EntropyModeFieldNumber = 5;
    private readonly static global::Variations.Layer.Types.EntropyMode EntropyModeDefaultValue = global::Variations.Layer.Types.EntropyMode.Default;

    private global::Variations.Layer.Types.EntropyMode entropyMode_;
    /// <summary>
    /// Which of the above entropy modes should be used to select a slot.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Variations.Layer.Types.EntropyMode EntropyMode {
      get { if ((_hasBits0 & 8) != 0) { return entropyMode_; } else { return EntropyModeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        entropyMode_ = value;
      }
    }
    /// <summary>Gets whether the "entropy_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEntropyMode {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "entropy_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEntropyMode() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Layer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Layer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NumSlots != other.NumSlots) return false;
      if(!members_.Equals(other.members_)) return false;
      if (Salt != other.Salt) return false;
      if (EntropyMode != other.EntropyMode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasNumSlots) hash ^= NumSlots.GetHashCode();
      hash ^= members_.GetHashCode();
      if (HasSalt) hash ^= Salt.GetHashCode();
      if (HasEntropyMode) hash ^= EntropyMode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasNumSlots) {
        output.WriteRawTag(16);
        output.WriteUInt32(NumSlots);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (HasSalt) {
        output.WriteRawTag(32);
        output.WriteUInt32(Salt);
      }
      if (HasEntropyMode) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EntropyMode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasNumSlots) {
        output.WriteRawTag(16);
        output.WriteUInt32(NumSlots);
      }
      members_.WriteTo(ref output, _repeated_members_codec);
      if (HasSalt) {
        output.WriteRawTag(32);
        output.WriteUInt32(Salt);
      }
      if (HasEntropyMode) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EntropyMode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (HasNumSlots) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumSlots);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (HasSalt) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Salt);
      }
      if (HasEntropyMode) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EntropyMode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Layer other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasNumSlots) {
        NumSlots = other.NumSlots;
      }
      members_.Add(other.members_);
      if (other.HasSalt) {
        Salt = other.Salt;
      }
      if (other.HasEntropyMode) {
        EntropyMode = other.EntropyMode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            NumSlots = input.ReadUInt32();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 32: {
            Salt = input.ReadUInt32();
            break;
          }
          case 40: {
            EntropyMode = (global::Variations.Layer.Types.EntropyMode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            NumSlots = input.ReadUInt32();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
          case 32: {
            Salt = input.ReadUInt32();
            break;
          }
          case 40: {
            EntropyMode = (global::Variations.Layer.Types.EntropyMode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Layer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum EntropyMode {
        /// <summary>
        /// Use the default entropy source when selecting slots. This will use the
        /// high entropy source for the clients that have it, and falls back to the
        /// low entropy source for other clients.
        /// </summary>
        [pbr::OriginalName("DEFAULT")] Default = 0,
        /// <summary>
        /// Use the low entropy source.
        /// </summary>
        [pbr::OriginalName("LOW")] Low = 1,
        /// <summary>
        /// Use the limited entropy source.
        /// </summary>
        [pbr::OriginalName("LIMITED")] Limited = 2,
      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class LayerMember : pb::IMessage<LayerMember>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<LayerMember> _parser = new pb::MessageParser<LayerMember>(() => new LayerMember());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<LayerMember> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Variations.Layer.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public LayerMember() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public LayerMember(LayerMember other) : this() {
          _hasBits0 = other._hasBits0;
          id_ = other.id_;
          slots_ = other.slots_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public LayerMember Clone() {
          return new LayerMember(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private readonly static uint IdDefaultValue = 0;

        private uint id_;
        /// <summary>
        /// An id (unique within the Layer) that studies will use to refer to this
        /// particular member.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Id {
          get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
          set {
            _hasBits0 |= 1;
            id_ = value;
          }
        }
        /// <summary>Gets whether the "id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasId {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearId() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "slots" field.</summary>
        public const int SlotsFieldNumber = 2;
        private static readonly pb::FieldCodec<global::Variations.Layer.Types.LayerMember.Types.SlotRange> _repeated_slots_codec
            = pb::FieldCodec.ForMessage(18, global::Variations.Layer.Types.LayerMember.Types.SlotRange.Parser);
        private readonly pbc::RepeatedField<global::Variations.Layer.Types.LayerMember.Types.SlotRange> slots_ = new pbc::RepeatedField<global::Variations.Layer.Types.LayerMember.Types.SlotRange>();
        /// <summary>
        /// Ranges of slots that belong to this member. These slot ranges must not
        /// overlap with the slot ranges of other members within the layer, so
        /// that at most one member within the layer will be active. The ranges must
        /// be listed in increasing order.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Variations.Layer.Types.LayerMember.Types.SlotRange> Slots {
          get { return slots_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as LayerMember);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(LayerMember other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if(!slots_.Equals(other.slots_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasId) hash ^= Id.GetHashCode();
          hash ^= slots_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasId) {
            output.WriteRawTag(8);
            output.WriteUInt32(Id);
          }
          slots_.WriteTo(output, _repeated_slots_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasId) {
            output.WriteRawTag(8);
            output.WriteUInt32(Id);
          }
          slots_.WriteTo(ref output, _repeated_slots_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasId) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
          }
          size += slots_.CalculateSize(_repeated_slots_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(LayerMember other) {
          if (other == null) {
            return;
          }
          if (other.HasId) {
            Id = other.Id;
          }
          slots_.Add(other.slots_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadUInt32();
                break;
              }
              case 18: {
                slots_.AddEntriesFrom(input, _repeated_slots_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Id = input.ReadUInt32();
                break;
              }
              case 18: {
                slots_.AddEntriesFrom(ref input, _repeated_slots_codec);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the LayerMember message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class SlotRange : pb::IMessage<SlotRange>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<SlotRange> _parser = new pb::MessageParser<SlotRange>(() => new SlotRange());
            private pb::UnknownFieldSet _unknownFields;
            private int _hasBits0;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<SlotRange> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Variations.Layer.Types.LayerMember.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SlotRange() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SlotRange(SlotRange other) : this() {
              _hasBits0 = other._hasBits0;
              start_ = other.start_;
              end_ = other.end_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SlotRange Clone() {
              return new SlotRange(this);
            }

            /// <summary>Field number for the "start" field.</summary>
            public const int StartFieldNumber = 1;
            private readonly static uint StartDefaultValue = 0;

            private uint start_;
            /// <summary>
            /// First slot in the range (inclusive). This range has to be
            /// in the [0..`num_slots`) range of the layer.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint Start {
              get { if ((_hasBits0 & 1) != 0) { return start_; } else { return StartDefaultValue; } }
              set {
                _hasBits0 |= 1;
                start_ = value;
              }
            }
            /// <summary>Gets whether the "start" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasStart {
              get { return (_hasBits0 & 1) != 0; }
            }
            /// <summary>Clears the value of the "start" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearStart() {
              _hasBits0 &= ~1;
            }

            /// <summary>Field number for the "end" field.</summary>
            public const int EndFieldNumber = 2;
            private readonly static uint EndDefaultValue = 0;

            private uint end_;
            /// <summary>
            /// Last slot in the range (inclusive).
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint End {
              get { if ((_hasBits0 & 2) != 0) { return end_; } else { return EndDefaultValue; } }
              set {
                _hasBits0 |= 2;
                end_ = value;
              }
            }
            /// <summary>Gets whether the "end" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasEnd {
              get { return (_hasBits0 & 2) != 0; }
            }
            /// <summary>Clears the value of the "end" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearEnd() {
              _hasBits0 &= ~2;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as SlotRange);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(SlotRange other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Start != other.Start) return false;
              if (End != other.End) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (HasStart) hash ^= Start.GetHashCode();
              if (HasEnd) hash ^= End.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (HasStart) {
                output.WriteRawTag(8);
                output.WriteUInt32(Start);
              }
              if (HasEnd) {
                output.WriteRawTag(16);
                output.WriteUInt32(End);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (HasStart) {
                output.WriteRawTag(8);
                output.WriteUInt32(Start);
              }
              if (HasEnd) {
                output.WriteRawTag(16);
                output.WriteUInt32(End);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (HasStart) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Start);
              }
              if (HasEnd) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(End);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(SlotRange other) {
              if (other == null) {
                return;
              }
              if (other.HasStart) {
                Start = other.Start;
              }
              if (other.HasEnd) {
                End = other.End;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    Start = input.ReadUInt32();
                    break;
                  }
                  case 16: {
                    End = input.ReadUInt32();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    Start = input.ReadUInt32();
                    break;
                  }
                  case 16: {
                    End = input.ReadUInt32();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  /// <summary>
  /// A Study can optionally specify a LayerMemberReference which will constrain it
  /// to one or more layer members of the specified layer.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LayerMemberReference : pb::IMessage<LayerMemberReference>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LayerMemberReference> _parser = new pb::MessageParser<LayerMemberReference>(() => new LayerMemberReference());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LayerMemberReference> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Variations.LayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayerMemberReference() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayerMemberReference(LayerMemberReference other) : this() {
      _hasBits0 = other._hasBits0;
      layerId_ = other.layerId_;
      layerMemberId_ = other.layerMemberId_;
      layerMemberIds_ = other.layerMemberIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayerMemberReference Clone() {
      return new LayerMemberReference(this);
    }

    /// <summary>Field number for the "layer_id" field.</summary>
    public const int LayerIdFieldNumber = 1;
    private readonly static uint LayerIdDefaultValue = 0;

    private uint layerId_;
    /// <summary>
    /// Reference to the layer with this specific ID.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LayerId {
      get { if ((_hasBits0 & 1) != 0) { return layerId_; } else { return LayerIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        layerId_ = value;
      }
    }
    /// <summary>Gets whether the "layer_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLayerId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "layer_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLayerId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "layer_member_id" field.</summary>
    public const int LayerMemberIdFieldNumber = 2;
    private readonly static uint LayerMemberIdDefaultValue = 0;

    private uint layerMemberId_;
    /// <summary>
    /// References to members within the above layer.
    ///
    /// New code should use `layer_member_ids` instead. Older clients only support
    /// `layer_member_id`, and values in `layer_member_ids` are ignored. Newer
    /// clients support both fields for backward compatibility. A study that uses
    /// `layer_member_ids` needs to have a `min_version` that is greater than
    /// the minimum version that supports `layer_member_ids`.
    /// TODO(crbug.com/345611804): Amend this comment with the minimum version when
    /// it is known.
    ///
    /// Specifying more than one `layer_member_id` can be used to adjust the active
    /// percentage of a study:
    ///   - Adding a `layer_member_id` will result in clients randomized to that
    ///     layer member to be part of this study (and be randomized into its
    ///     groups).
    ///   - Removing a `layer_member_id` will take out clients randomized to that
    ///     layer member from the study.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LayerMemberId {
      get { if ((_hasBits0 & 2) != 0) { return layerMemberId_; } else { return LayerMemberIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        layerMemberId_ = value;
      }
    }
    /// <summary>Gets whether the "layer_member_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLayerMemberId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "layer_member_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLayerMemberId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "layer_member_ids" field.</summary>
    public const int LayerMemberIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_layerMemberIds_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> layerMemberIds_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LayerMemberIds {
      get { return layerMemberIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LayerMemberReference);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LayerMemberReference other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LayerId != other.LayerId) return false;
      if (LayerMemberId != other.LayerMemberId) return false;
      if(!layerMemberIds_.Equals(other.layerMemberIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLayerId) hash ^= LayerId.GetHashCode();
      if (HasLayerMemberId) hash ^= LayerMemberId.GetHashCode();
      hash ^= layerMemberIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLayerId) {
        output.WriteRawTag(8);
        output.WriteUInt32(LayerId);
      }
      if (HasLayerMemberId) {
        output.WriteRawTag(16);
        output.WriteUInt32(LayerMemberId);
      }
      layerMemberIds_.WriteTo(output, _repeated_layerMemberIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLayerId) {
        output.WriteRawTag(8);
        output.WriteUInt32(LayerId);
      }
      if (HasLayerMemberId) {
        output.WriteRawTag(16);
        output.WriteUInt32(LayerMemberId);
      }
      layerMemberIds_.WriteTo(ref output, _repeated_layerMemberIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLayerId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LayerId);
      }
      if (HasLayerMemberId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LayerMemberId);
      }
      size += layerMemberIds_.CalculateSize(_repeated_layerMemberIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LayerMemberReference other) {
      if (other == null) {
        return;
      }
      if (other.HasLayerId) {
        LayerId = other.LayerId;
      }
      if (other.HasLayerMemberId) {
        LayerMemberId = other.LayerMemberId;
      }
      layerMemberIds_.Add(other.layerMemberIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LayerId = input.ReadUInt32();
            break;
          }
          case 16: {
            LayerMemberId = input.ReadUInt32();
            break;
          }
          case 26:
          case 24: {
            layerMemberIds_.AddEntriesFrom(input, _repeated_layerMemberIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LayerId = input.ReadUInt32();
            break;
          }
          case 16: {
            LayerMemberId = input.ReadUInt32();
            break;
          }
          case 26:
          case 24: {
            layerMemberIds_.AddEntriesFrom(ref input, _repeated_layerMemberIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
