name: Deploy

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone publish
        run: git clone --depth 1 --branch publish https://github.com/uazo/superpatch out/wwwroot

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Build & Publish
        run: dotnet publish -c Release -o out

      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to superpatch
        run: sed -i 's/<base href="\/" \/>/<base href="\/superpatch\/" \/>/g' out/wwwroot/index.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch out/wwwroot/.nojekyll

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp out/wwwroot/index.html out/wwwroot/404.html

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          base: publish
          path: out/wwwroot
          delete-branch: true
          
